#!/usr/bin/env bash
#
# Tests for scripts/review.sh — the Stop-hook trigger logic.
#
# Black-box: we craft a fake transcript + hook payload, run the real hook
# script, and assert on the JSON it prints to stdout. Covers the decision to
# review, the docs/lockfile/generated skip filter, per-session deduplication,
# audience selection, and the fail-open silent paths.
#
# Run: bash tests/test_review.sh   (exits non-zero if any test fails)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK="$REPO_ROOT/scripts/review.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Isolate dedup state files ($TMPDIR is honored by python's tempfile) from any
# real sessions on this machine.
export TMPDIR="$WORK/tmp"
mkdir -p "$TMPDIR"

PROJECT_DIR="$WORK/proj"
mkdir -p "$PROJECT_DIR/.claude"

# A controlled, empty user-home so the user-wide audience fallback
# (~/.claude/review-audience) is deterministic regardless of the real home.
# Tests that need a global marker write to $GLOBAL_HOME/.claude/review-audience.
GLOBAL_HOME="$WORK/home"
mkdir -p "$GLOBAL_HOME/.claude"

pass=0
fail=0

ok() { pass=$((pass + 1)); printf '  PASS: %s\n' "$1"; }
no() { fail=$((fail + 1)); printf '  FAIL: %s\n' "$1"; }

# run_hook <session_id> <transcript_file> [stop_hook_active] -> prints stdout
run_hook() {
    local sid="$1" transcript="$2" active="${3:-false}"
    printf '{"transcript_path":"%s","session_id":"%s","stop_hook_active":%s}' \
        "$transcript" "$sid" "$active" \
        | HOME="$GLOBAL_HOME" CLAUDE_PROJECT_DIR="$PROJECT_DIR" CLAUDE_PLUGIN_ROOT="$REPO_ROOT" \
            bash "$HOOK"
}

# edit_line <path> -> a transcript line representing an Edit tool_use
edit_line() {
    printf '{"message":{"content":[{"type":"tool_use","name":"Edit","input":{"file_path":"%s"}}]}}\n' "$1"
}

assert_contains() { case "$2" in *"$3"*) ok "$1" ;; *) no "$1 (missing: $3)" ;; esac; }
assert_not_contains() { case "$2" in *"$3"*) no "$1 (unexpected: $3)" ;; *) ok "$1" ;; esac; }
assert_empty() { if [ -z "$2" ]; then ok "$1"; else no "$1 (expected silence, got: $2)"; fi; }

# ---------------------------------------------------------------------------
echo "test: reviews a normal edited source file"
t="$WORK/t1.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-1 "$t")
assert_contains "emits block decision" "$out" '"decision": "block"'
assert_contains "lists the source file" "$out" "/proj/src/app.py"

# ---------------------------------------------------------------------------
echo "test: skips docs, lockfiles, and generated files by path"
t="$WORK/t2.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
edit_line "/proj/README.md" >>"$t"
edit_line "/proj/docs/guide.rst" >>"$t"
edit_line "/proj/package-lock.json" >>"$t"
edit_line "/proj/web/app.min.js" >>"$t"
edit_line "/proj/api/service_pb2.py" >>"$t"
edit_line "/proj/node_modules/dep/index.js" >>"$t"
out=$(run_hook sid-2 "$t")
assert_contains "still reviews the source file" "$out" "/proj/src/app.py"
assert_not_contains "skips README.md" "$out" "README.md"
assert_not_contains "skips .rst doc" "$out" "guide.rst"
assert_not_contains "skips lockfile" "$out" "package-lock.json"
assert_not_contains "skips .min.js" "$out" "app.min.js"
assert_not_contains "skips protobuf _pb2.py" "$out" "service_pb2.py"
assert_not_contains "skips node_modules path" "$out" "node_modules"

# ---------------------------------------------------------------------------
echo "test: silent when every edited file is skippable"
t="$WORK/t3.jsonl"; : >"$t"
edit_line "/proj/README.md" >>"$t"
edit_line "/proj/yarn.lock" >>"$t"
out=$(run_hook sid-3 "$t")
assert_empty "no decision when nothing reviewable" "$out"

# ---------------------------------------------------------------------------
echo "test: skips files with a generated header marker"
gen="$PROJECT_DIR/gen_config.py"
printf '# Code generated by tool. DO NOT EDIT.\nx = 1\n' >"$gen"
t="$WORK/t4.jsonl"; : >"$t"
edit_line "$gen" >>"$t"
edit_line "/proj/src/real.py" >>"$t"
out=$(run_hook sid-4 "$t")
assert_contains "reviews the hand-written file" "$out" "/proj/src/real.py"
assert_not_contains "skips DO NOT EDIT file" "$out" "gen_config.py"

# ---------------------------------------------------------------------------
echo "test: does not re-review the same file within a session"
t="$WORK/t5.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out1=$(run_hook sid-5 "$t")
assert_contains "first turn reviews" "$out1" "/proj/src/app.py"
out2=$(run_hook sid-5 "$t")
assert_empty "second turn stays silent" "$out2"

# ---------------------------------------------------------------------------
echo "test: plain audience produces a non-technical instruction"
echo plain >"$PROJECT_DIR/.claude/review-audience"
t="$WORK/t6.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-6 "$t")
assert_contains "uses plain-English framing" "$out" "NOT a programmer"
rm -f "$PROJECT_DIR/.claude/review-audience"

# ---------------------------------------------------------------------------
echo "test: user-wide plain audience (no project marker) produces plain framing"
echo plain >"$GLOBAL_HOME/.claude/review-audience"
t="$WORK/t6b.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-9 "$t")
assert_contains "global plain marker applies" "$out" "NOT a programmer"

# ---------------------------------------------------------------------------
echo "test: a project marker overrides the user-wide default"
echo technical >"$PROJECT_DIR/.claude/review-audience"   # global still 'plain' from above
t="$WORK/t6c.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-10 "$t")
assert_contains "project technical wins over global plain" "$out" "grouped by severity"
assert_not_contains "no plain framing when project overrides" "$out" "NOT a programmer"
rm -f "$PROJECT_DIR/.claude/review-audience" "$GLOBAL_HOME/.claude/review-audience"

# ---------------------------------------------------------------------------
echo "test: neither marker present falls back to technical"
t="$WORK/t6d.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-11 "$t")
assert_contains "defaults to technical framing" "$out" "grouped by severity"
assert_not_contains "no plain framing by default" "$out" "NOT a programmer"

# ---------------------------------------------------------------------------
echo "test: stop_hook_active short-circuits to silence"
t="$WORK/t7.jsonl"; : >"$t"
edit_line "/proj/src/app.py" >>"$t"
out=$(run_hook sid-7 "$t" true)
assert_empty "no decision on continuation" "$out"

# ---------------------------------------------------------------------------
echo "test: missing transcript stays silent"
out=$(run_hook sid-8 "$WORK/nope.jsonl")
assert_empty "no decision without transcript" "$out"

# ---------------------------------------------------------------------------
printf '\n%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
